### ISSUE TITLE
Order email: Listing image is not displaying

### ISSUE THREAD

**Issue by morebrownies** [OB1Company/filehive#20]
**To do**

- [ ] 1. I received an order and I noticed the image isn't displaying

<img width="682" alt="Screen Shot 2021-02-11 at 11 04 24 AM" src="https://user-images.githubusercontent.com/13066886/107685699-2561fd00-6c59-11eb-8437-1ce5d8c666e3.png">

**Comment by hoffmabc** [comment]
I can't reproduce this.

**Comment by morebrownies** [comment]
I'm going to close it. I noticed other emails (outside of Filehive) also have dead image in my email. Might be a problem on my end.
