### ISSUE TITLE
Checkout: Confirm Order button is failing without an error message

### ISSUE THREAD

**Issue by morebrownies** [OB1Company/filehive#31]
**Issue**

- [ ] 1. I'm clicking **Confirm Order** during checkout but it appears to fail without any error message. I checked my Wallet and confirmed I have enough funds to make the purchase. 

https://user-images.githubusercontent.com/13066886/107991381-5ad55600-6f8b-11eb-9c4d-42f5ba53de80.mov

**Comment by hoffmabc** [comment]
Do you see any errors in the JavaScript consul or the network tab?￼

**Comment by morebrownies** [comment]
This is in the **console** tab

<img width="1161" alt="Screen Shot 2021-02-15 at 1 12 03 PM" src="https://user-images.githubusercontent.com/13066886/107993499-6a569e00-6f8f-11eb-9d25-1859e0038c6a.png">

VM323:1 POST https://beta.filehive.app/api/v1/purchase/1AYsjaF5mh31dzJLpJPnsHAqH66GiweE8rqwwXeEy2Q7gj 504 (Gateway Timeout)
(anonymous) @ VM323:1
dispatchXhrRequest @ xhr.js:177
xhrAdapter @ xhr.js:13
dispatchRequest @ dispatchRequest.js:52
Promise.then (async)
request @ Axios.js:61
Axios.<computed> @ Axios.js:87
wrap @ bind.js:9
sendPayment @ DatasetPage.js:82
HandleClickPurchase @ DatasetPage.js:93
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
DatasetPage.js:90 Error: Request failed with status code 504
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:62)

**Comment by hoffmabc** [comment]
I think I was futzing with the server. Still need to handle the error though.
