### ISSUE TITLE
Listing details: Automatic scrolling when loading the listing detail view

### ISSUE THREAD

**Issue by morebrownies** [OB1Company/filehive#32]
**Issue**

- [ ] 1. When I click on a listing further down the home page, I noticed it automatically scrolls me to the same position on the listing detail page. Check out the video below.

https://user-images.githubusercontent.com/13066886/107991792-2e6e0980-6f8c-11eb-991f-e89ce4ccb248.mov

**Comment by hoffmabc** [comment]
Ok maybe we need a scroll to top function. https://reactrouter.com/web/guides/scroll-restoration

**Comment by hoffmabc** [comment]
I'm not seeing this in Chrome. Are you using Safari @morebrownies ?

**Comment by morebrownies** [comment]
I was using Chrome

**Comment by morebrownies** [comment]
I'm not seeing it happen on Chrome anymore...
