### ISSUE TITLE
Edit Listing: Add view listing button/link

### ISSUE THREAD

**Issue by morebrownies** [OB1Company/filehive#33]
**Changes**

- [ ] 1. It can be difficult to navigate to your own listings. Currently, you have to find your listing on the home page and click it to view it. Once there are many more listings, finding your listing easily on the home page may not be possible. To solve this issue, we should add a **View listing** button/link to the edit listing page. 

See video below (turn your sound on)

https://user-images.githubusercontent.com/13066886/107992406-7e999b80-6f8d-11eb-923d-2e937357cd23.mov

**Comment by hoffmabc** [comment]
I made the title and image for the listing clickable to navigate to the actual listing page. Does this work @morebrownies ?

**Comment by morebrownies** [comment]
Yeah, great!
